### ISSUE TITLE
Set always pull image

### ISSUE THREAD

**Issue by solocommand** [jenkinsci/rancher-plugin#4]
Hello,

Is it possible to set the "Always pull image when creating" flag with this plugin? Or to set the `io.rancher.container.pull_image` label?

**Comment by yunlzheng** [comment]
@solocommand This is not support with this plugin now. and i think it should be better to control the image pull policy in rancher ui.

**Comment by solocommand** [comment]
@yunlzheng Thanks for the response. The problem i was running into is when a service does not exist, the plugin creates it based on the stack/service name used. But in order for subsequent deployments to show changes, I have to upgrade the service and check always pull.

Is there a reason that you wouldn't want the image to be pulled when performing an upgrade via the plugin?

And I know it's off-scope, but do you know if there's a configuration option for Rancher to set the image pull policy globally?

**Comment by yunlzheng** [comment]
@solocommand I think the main reason why you need this is because the image tag never change.
And in my option,  the best practice in container base continuous delivery you should consider to change the image tag strange for example: 

* "namespace/repo:${BUILD_NUMBER}"
* "namespace/repo:${TIMESTAMP}"
* "namespace/repo:${BRANCH}-${BUILD_NUMBER}"

```
docker build -t namespace/repo:${BUILD_NUMBER} .
```

if you do that, this can give you change to rollback when the business is broken by the new build image. and also make connection between **jenkins build/code commit** and the container image.
And this plugin current support the build environment variable in image field.

**Comment by solocommand** [comment]
@yunlzheng Awesome, thank you! I'm actually tagging both `latest` and the build number on build, I'll switch my deployment to use the build number for the image instead of latest. Didn't even occur to me to do that -- thanks!
